Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine311"
  config.vm.synced_folder ".", "/vagrant"

  # Server Machine
  config.vm.define "abel-bouS" do |server|
    server.vm.hostname = "abel-bouS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider"virtualbox" do |vb|
      vb.name = "abel-bouS-p2"
      vb.memory = "2048"
      vb.cpus = 2
    end

    # Script
    server.vm.provision "shell", path: "scripts/install_k3s_and_apps.sh"
  end

end
