Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # Server Machine
  config.vm.define "abel-bouS" do |server|
    server.vm.hostname = "abel-bouS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider"virtualbox" do |vb|
      vb.name = "abel-bouS-p2"
      vb.memory = "2048"
      vb.cpus = 1
    end

    # Script
    
    # server.vm.provision"shell", inline:<<-SHELL
    # apt-get update
    # SHELL
    server.vm.provision "shell", path: "scripts/install_k3s_and_apps.sh"
  end

end
