Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine311"
  config.vm.synced_folder ".", "/vagrant"


  # Server Machine
  config.vm.define "abel-bouS" do |server|
    server.vm.hostname = "abel-bouS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider"virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"

  end

  # Server Worker Machine
  config.vm.define "abel-bouSW" do |worker|
    worker.vm.hostname = "abel-bouSW"
    worker.vm.network "private_network", ip:"192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"

  end

end
